policies:
- path: /tmp/filejanitor/1/10s-5
  keep_last: 5
  scan_every: 10s
  retention_period: 10s
- path: /tmp/filejanitor/1/1m-3
  keep_last: 3
  extension: log
  scan_every: 10s
  retention_period: 1m
- path: /tmp/filejanitor/1/5m-1
  keep_last: 1
  extension: txt
  scan_every: 10s
  retention_period: 5m0s
- path: /tmp/filejanitor/2/10s-5
  keep_last: 5
  scan_every: 10s
  retention_period: 10s
- path: /tmp/filejanitor/2/1m-3
  keep_last: 3
  extension: log
  scan_every: 10s
  retention_period: 1m
- path: /tmp/filejanitor/2/5m-1
  keep_last: 1
  extension: txt
  scan_every: 10s
  retention_period: 5m0s
- path: /tmp/filejanitor/3/10s-5
  keep_last: 5
  scan_every: 10s
  retention_period: 10s
- path: /tmp/filejanitor/3/1m-3
  keep_last: 3
  extension: log
  scan_every: 10s
  retention_period: 1m
- path: /tmp/filejanitor/3/5m-1
  extension: txt
  keep_last: 1
  scan_every: 10s
  retention_period: 5m0s
